#+startup: beamer
#+title: Advanced mixed-models workshop: Session 5
#+author: Dale Barr
#+email: dale.barr@glasgow.ac.uk
#+date: Bremen March 2015
#+OPTIONS: toc:nil H:2 ^:nil
#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: []
#+BEAMER_THEME: Boadilla
#+LATEX_HEADER: \makeatletter \def\verbatim{\scriptsize\@verbatim \frenchspacing\@vobeyspaces \@xverbatim} \makeatother

#+BEAMER_COLOR_THEME: seahorse
#+LATEX_HEADER: \definecolor{lgray}{rgb}{0.90,0.90,0.90}
#+LATEX_HEADER: \beamertemplatenavigationsymbolsempty
#+LATEX_HEADER: \usemintedstyle{tango}
#+LATEX_HEADER: \institute{University of Glasgow}

#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)

#+PROPERTY: header-args:R :session *R* :exports both :results output :tangle session_05.R

* Setup 																													 :noexport:

** Formatting

#+name: setup-minted
#+begin_src emacs-lisp :exports none :results silent
(setq org-src-preserve-indentation t)
(setq org-latex-minted-options
			'(("frame" "none")
				("fontsize" "\\scriptsize")
				("linenos" "false")
				("bgcolor" "lgray")
				("tabsize" "2")
				))
#+end_src

* GLMs

** Continuous vs. discrete data

Two discrete types of data are common in psychology/linguistics

- categorical (dichotomous/polychotomous)
  - type of linguistic structure produced (X, Y, Z)
  - region looked at in a visual world study (target, other)
  - number of items recalled out of N
  - accurate or inaccurate selection

- counts (no. opportunities ill-defined)
  - no. of speech errors in a corpus
  - no. of turn shifts in a conversation
  - no. words in a utterance

** Why not treat discrete data as continuous?
- Proportions range between 0 and 1
- Variance proportional to the mean (expected probability or rate)
- Spurious interactions due to scaling effects (see Jaeger, 2008)

** Generalized linear models

- Allows use of regular linear regression by projecting the DV onto an
  appropriate scale

- Key elements of GLMs: 
  - link function
  - variance function

** Odds and log odds

#+BEGIN_LaTeX
\begin{description}[Bernoulli trial]

\item[Bernoulli trial] An event that has a binary outcome, with one
  outcome typically referred to as ``success''

\item[proportion] A ratio of successes to the total number of
  Bernoulli trials, proportion of days of the week that are Wednesday
  is 1/7 or about .14

\item[odds] A ratio of successes to non-successes, i.e., odds of a
  day being Wednesday are 1 to 6, natural odds= 1/6 = .17

\item[log odds] The (natural) log of the odds (turns multiplicative
  effects into additive effects)

\end{description}
#+END_LaTeX

** Properties of log odds or ``logit''

log odds: $log\left(\frac{p}{1-p}\right)$ or $log\left(\frac{Y}{N-Y}\right)$

where $p$ is a proportion, $N$ is total trials and $Y$ is observed successes

- Scale goes from \(-\infty\) to \(+\infty\)
- Scale is symmetric around zero
- If negative, means that Pr(success)\(<.5\)
- If positive, Pr(success)\(>.5\)

** Logistic regression

#+BEGIN_LaTeX
\begin{columns}[T]
\begin{column}{.5\textwidth}
DV has 2 categories\\[6pt]
\structure{model}\\
$\eta = \beta_0 + \beta_1 X$\\
\vspace{6pt}
\structure{link function}\\
$\eta = log\left(\frac{p}{1-p}\right)$\\
\vspace{6pt}
\structure{inverse link function}\\
$p = \frac{1}{1+exp(-\eta)}$\\
getting odds from logit: exp($\eta$)\\
\vspace{6pt}
\structure{variance function} (binomial)\\
$np(1-p)$\\
\end{column}
\begin{column}{.5\textwidth}
\includegraphics[scale=.4]{img/logit}
\end{column}
\end{columns}
#+END_LaTeX

* Data analysis

** Load in and prepare the data

#+BEGIN_SRC R
  dat <- readRDS("FAN.rds")
  dat1 <- subset(dat, Day == 2)

  dat1 <- transform(dat1,
                    V1 = (Cond == "same voice") -
                        mean(Cond == "same voice"),
                    V2 = (Cond == "same gender, different voice") -
                        mean(Cond == "same gender, different voice"))
#+END_SRC

** Fit a model

- use =glmer()= with optimizer "bobyqa"

#+BEGIN_SRC R :cache yes
  library("lme4")

  mod <- glmer(Accuracy ~ V1 + V2 +
                   (V1 + V2 | SessionID) +
                   (V1 + V2 | ItemID),
               data = dat1, family = binomial(link = logit),
               control = glmerControl(optimizer = "bobyqa"))
#+END_SRC

#+RESULTS[9c5318579f29c45d8d8959e6b042367dd4277e6b]:

** View results

#+BEGIN_SRC R :exports results
  summary(mod)
#+END_SRC

#+RESULTS:
#+begin_example
Generalized linear mixed model fit by maximum likelihood (Laplace
  Approximation) [glmerMod]
 Family: binomial  ( logit )
Formula: Accuracy ~ V1 + V2 + (V1 + V2 | SessionID) + (V1 + V2 | ItemID)
   Data: dat1
Control: glmerControl(optimizer = "bobyqa")

     AIC      BIC   logLik deviance df.resid 
  4149.4   4249.3  -2059.7   4119.4     5745 

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-12.1153   0.1436   0.2594   0.4351   1.3263 

Random effects:
 Groups    Name        Variance  Std.Dev. Corr       
 ItemID    (Intercept) 0.4185370 0.64694             
           V1          0.0202878 0.14244   0.14      
           V2          0.0118758 0.10898  -1.00 -0.17
 SessionID (Intercept) 1.3562216 1.16457             
           V1          0.0004334 0.02082   1.00      
           V2          0.0008073 0.02841  -1.00 -1.00
Number of obs: 5760, groups:  ItemID, 96; SessionID, 20

Fixed effects:
            Estimate Std. Error z value Pr(>|z|)    
(Intercept)  2.30963    0.27516   8.394   <2e-16 ***
V1           0.03101    0.13817   0.224    0.822    
V2           0.09727    0.13859   0.702    0.483    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation of Fixed Effects:
   (Intr) V1    
V1  0.042       
V2 -0.059  0.483
#+end_example

** Multiparameter test

#+BEGIN_SRC R :cache yes
  mod2 <- update(mod, . ~ . - V1 - V2)

  anova(mod, mod2)
#+END_SRC

#+RESULTS[4c68ebce9d6f2bccff7dbb0e31316bcadb39a9ad]:
: Data: dat1
: Models:
: mod2: Accuracy ~ (V1 + V2 | SessionID) + (V1 + V2 | ItemID)
: mod: Accuracy ~ V1 + V2 + (V1 + V2 | SessionID) + (V1 + V2 | ItemID)
:      Df    AIC    BIC  logLik deviance  Chisq Chi Df Pr(>Chisq)
: mod2 13 4145.9 4232.4 -2059.9   4119.9                         
: mod  15 4149.4 4249.3 -2059.7   4119.4 0.4632      2     0.7933

** Conditional versus marginal probabilities

#+BEGIN_SRC R
  pmean <- aggregate(Accuracy ~ Cond, dat, mean)

  int <- fixef(mod)
  params <- fixef(mod)[-1]

  mx <- matrix(c(-1/3,  2/3, -1/3,
                 -1/3, -1/3,  2/3), ncol = 2)

  df1 <- data.frame(Cond = c("different gender, different voice",
                     "same voice",
                     "same gender, different voice"),
             logit = as.numeric(mx %*% params + fixef(mod)[1]))
  df1$pmod = 1 / (1 + exp(-df1$logit))

  merge(df1, pmean)
#+END_SRC
** Interpreting results: Odds ratios

- use the =exp()= function to get odds ratios

The \(\beta\) associated with =V1= is the change (in logit space)
associated with hearing the name in the same voice as in training
vs. a different voice

How does that "change the odds" of clicking the right person?

#+BEGIN_SRC R
  c(params["V1"], OR = exp(params["V1"]))
#+END_SRC

#+RESULTS:
:         V1      OR.V1 
: 0.03101181 1.03149769

